name: mobaitec_decision_making
description: 'Application de prise de décision Mobaitec'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  desktop_window: ^0.4.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  parse_server_sdk_flutter: ^8.0.0
  path_provider: ^2.1.5
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/mobaitec-logo.png
    - assets/keycloak.png
    - lib/data/rsp-bgs/
    - lib/data/rsp-neg/
    - lib/data/rsp-sb/
